### PR TITLE
rename 64-bit and debug binaries

### PR DESCRIPTION
**Pull request by aleks-f**
- replace "32" with "64" suffix for 64-bit binaries
- add "d" suffix to debug binaries
- separate .nupkg files for 32 and 64 bit

### CODE REVIEW

**Comment by vktr** [comment]
Instead of renaming binaries and separating NuGet package files, I'd rather keep the naming of the binaries as-is and include both the win32 and win64 libs and dlls in the one NuGet package.

At least, that is what I had in mind when putting a `win32/` folder in the .nupkg root.

What do you think?

**Comment by aleks-f** [comment]
That's ok with me, the reason I am working on this is to include it in poco and we don't need nuget there anyway. I have also added static build (not pushed yet) and would definitely like to keep files renamed (if something else doesn't come in the way of preventing it objectively, I did not yet try to build poco with it). I find having 32 and 64, static and dynamic, release and debug binary files named the same an atrocious practice. It would be a little bit less atrocious if it didn't have "32" in the name.

I could change things so everything can be provided through command line parameters, with defaults compatible with your requirements, that way we can keep code synced. Otherwise, we can fork and go our own marry ways ;)

**Comment by vktr** [comment]
AFAIK you cannot just rename the dll file. The application will fail to load it at runtime unless you do some delayed loading magic. For this to work you need to hook into the OpenSSL and make it output the correct file names.

My main concern with different file names is that I specify dependencies in my CMakeLists and not in some `#pragma lib`, otherwise I agree with you on the naming. In the best of worlds we'd skip the `win32/` and `win64/` folders and just keep all binaries in the same folder.

If you manage to make OpenSSL output correct file names I'll accept it and adapt my build scripts accordingly.

**Comment by aleks-f** [comment]
I think you are right, I did not try to link/run yet, although just renaming the *.lib stub for DLL should work fine. I will look into it

**Comment by aleks-f** [comment]
OK, after some gymnastics I've got it working properly (even emitting the PDB). Tested compile and testrun for all platforms and configurations; [Poco merge](https://github.com/pocoproject/poco/blob/OpenSSLBuild/openssl/build.ps1) (without nuget portion) is pending in a separate branch, let me know if you are interested and I'll send you pull with nuget portion.

**Pull request closed without merging**
